### PR TITLE
Allow sending method rpcs immediately

### PR DESCRIPTION
**Pull request by simonkellly**

### CODE REVIEW

**Comment by DorCoMaNdO** [comment]
Adding a `SendImmediately` method will probably simpler and more suitable for RPCs with multiple uses.

**Comment by simonkellly** [comment]
Not sure i understand what you mean, the option for making a method rpc is done in the attribute not in the method itself

**Comment by DorCoMaNdO** [comment]
Sending it is done via a call to `Send`, which you've now altered to support sending immediately, instead just add a separate method.

**Comment by simonkellly** [comment]
Unsafe send always had support for sending immediately, it was an optional parameter. This pr just exposes a way to set said optional parameter inside a method rpc, it does not touch the rest of the rpc system

**Pull request merged**
